### ISSUE TITLE
About the modified code mentioned in the paper

### ISSUE THREAD

**Issue by Zorinman** [jovans2/MXFaaS_Artifact#11]
Hello!
Quoting from the paper
>  "We changed the implementations of OpenWhisk’s invoker and load balancer [54, 55]. The invoker works with MXContainers in addition to traditional containers: it is informed of the MXContainer load and allocates CPU cores accordingly. The load balancer is informed of any MXContainer overload. The modifications required about 400 lines of Scala code. For KNative, we modified the autoscaler and activator [38, 39], which play a similar role as the load balancer and invoker in OpenWhisk. The modification is identical to that of OpenWhisk but written in about 300 lines of Go code."

Question:  Is the modified code available in the source code?what parts of the code correspond to these code? If not, will it affect the reproducibility of the paper's results? (I haven't deeply studied the entire paper, so please correct me if I'm wrong.) Thank you!

**Comment by jovans2** [comment]
Hello, the open-sourced version of MXFaaS is slightly modified to better support modularity. Instead of modifying the existing components, we have implemented a new component (Node Controller — https://github.com/jovans2/MXFaaS_Artifact/blob/main/KNative_prototype/nodeController.py). The node controller checks the statistics of the individual active functions and changes the core mappings accordingly. The performance on a single node is equivalent to the paper performance. However, to fully support MXFaaS as described in the paper and run in a distributed environment, you would only need to add a connection between Node Controller and Autoscaler to create another instance of a given function on some other node when the function becomes overloaded.

Let us know if you have any other issues and we will try to help with those.

**Comment by Zorinman** [comment]
Appreciate  it ！If there are any difficulties that cannot be resolved, I will ask for your help again:D
