### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by guanchenY** [jovans2/MXFaaS_Artifact#5]
I want to know that how to use nodeController.py,cpu_utils.py.  Or to put it another way, when do I use these files？Thank you !

**Comment by jovans2** [comment]
Hello, 
1) cpu_utils.py is used to measure the CPU utilization of a container with "docker stats" command
2) nodeController.py is used to assign cores on your servers across co-located containers -- based on the needs of these containers, node controller decides how many CPUs are needed for each of them.
Hope this helps, if not, let me know what else is confusing. Thank you!

**Comment by GitHubDiom** [comment]
I have some questions about the use of `nodeController.py`. 

The README mentions two experiments, `python3 knative_all.py` and `python3 run-all.py`. 
One runs on the Knative platform and the other experiment actually evaluates the performance of `runner.py` in a container. 

None of the experiments seem to involve `NodeController.py`. 
So, how is the `updateThread` in `runner.py` actually activated? 
From the code, it looks like a thread is listening on port 5500. 
Since I haven't observed the running of `NodeController.py`, I can't tell where requests to port 5500 are coming from.

**Comment by GitHubDiom** [comment]
I have previously submitted another [related Issue](https://github.com/jovans2/MXFaaS_Artifact/issues/2#issue-1696960955), but I still have questions about the use of NodeController.py. 

I would appreciate any response.
Thanks
